name: Deploy Docs to Cloudflare

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PUBLIC_POSTHOG_KEY: ${{ secrets.PUBLIC_POSTHOG_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9.1.0

      # enable cache to download only the different packages -> more quickly
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"

      - uses: oven-sh/setup-bun@v2 # install bun to run the sync script
      - run: pnpm install --frozen-lockfile
      - run: pnpm run sync --yes
      - run: pnpm --filter icons build

      - name: Check working directory
        run: |
          grep -n "solidPersonWalking" ./packages/icons/dist/ev-icon.es.js

      - run: pnpm --filter docs build
      - run: pnpm add -w -D wrangler@3.90.0

      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          preCommands: |
            wrangler pages project list | grep -q "${{ secrets.CLOUDFLARE_DOCS_NAME }}" && echo "Project already exists, continuing." || wrangler pages project create ${{ secrets.CLOUDFLARE_DOCS_NAME }} --production-branch=main

            echo "${{ secrets.PUBLIC_POSTHOG_KEY }}" > PUBLIC_POSTHOG_KEY.txt
            wrangler pages secret put PUBLIC_POSTHOG_KEY --project-name ${{ secrets.CLOUDFLARE_PROJECT_NAME }} < PUBLIC_POSTHOG_KEY.txt
            rm PUBLIC_POSTHOG_KEY.txt
          # preCommands: |
          #   wrangler pages project list
          #   wrangler pages project create ${{ secrets.CLOUDFLARE_DOCS_NAME }} --production-branch=main || true

          # export PUBLIC_POSTHOG_KEY="${{ secrets.PUBLIC_POSTHOG_KEY }}"
          command: pages deploy apps/docs/dist --project-name=${{ secrets.CLOUDFLARE_DOCS_NAME }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
