name: Deploy Docs to Cloudflare

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9.1.0

      # enable cache to download only the different packages -> more quickly
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"

      - uses: oven-sh/setup-bun@v2 # install bun to run the sync script
      - run: pnpm install --frozen-lockfile
      - run: pnpm run sync --yes
      - run: pnpm --filter icons build

      - name: Check working directory
        run: |
          grep -n "solidPersonWalking" ./packages/icons/dist/ev-icon.es.js

        # echo "Current working directory:"
        # pwd
        # echo "-----------------------------------"
        # echo "Listing files recursively from current directory:"
        # find . \
        #   -path './node_modules' -prune -o \
        #   -path '*/node_modules' -prune -o \
        #   -path './apps/docs/public/icons' -prune -o \
        #   -path './packages/icons/src/assets' -prune -o \
        #   -print
        # echo "-----------------------------------"

      - run: pnpm --filter docs build
      - run: pnpm add -w -D wrangler@3.90.0

      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          preCommands: |
            wrangler pages project list
            wrangler pages project create ${{ secrets.CLOUDFLARE_DOCS_NAME }} --production-branch=main || true
          command: pages deploy apps/docs/dist --project-name=${{ secrets.CLOUDFLARE_DOCS_NAME }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
